id: I8841A8DC
legacy_id: P006774
ocr_import_info:
  bdrc_scan_id: W1KG8837
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T19:09:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:05:41.471140+00:00'
last_modified: 2022-09-01 02:06:43.214898
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG8837
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG8837
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཞུང་ཆེན་བཅུ་གསུམ་གྱི་མཆན་འགྲེལ་ལས་མདོ་སྡེའི་རྒྱན་དང་ཤེར་ཕྱིན་སོགས་ཀྱི་མཆན་འགྲེལ་ཁག་ཅིག
  author: རྒྱ་ཀོང་མཁན་ཆེན་གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.6766286134261655
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG12276:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12276
      total_pages: 430
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12276.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7253567502068262
    legacy_id: v001
  I1KG22020:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22020
      total_pages: 1412
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22020.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6638995695331618
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
