id: I8841A8DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T19:12:07+00:00'
last_modified: '2022-06-08T06:45:57.260258+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8837
  title: གཞུང་ཆེན་བཅུ་གསུམ་གྱི་མཆན་འགྲེལ་ལས་མདོ་སྡེའི་རྒྱན་དང་ཤེར་ཕྱིན་སོགས་ཀྱི་མཆན་འགྲེལ་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5D76:
      image_group_id: I1KG12276
      title: ''
      total_pages: 430
      order: 1
      base_file: 5D76.txt
    93B9:
      image_group_id: I1KG22020
      title: ''
      total_pages: 1412
      order: 2
      base_file: 93B9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
