id: P006774
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8837
  title: གཞུང་ཆེན་བཅུ་གསུམ་གྱི་མཆན་འགྲེལ་ལས་མདོ་སྡེའི་རྒྱན་དང་ཤེར་ཕྱིན་སོགས་ཀྱི་མཆན་འགྲེལ་ཁག་ཅིག
  author: ''
  volumes:
    bcf03513abb246af9807d35fc1518e9b:
      image_group_id: I1KG12276
      title: ''
      volume_number: 1
      total_pages: 430
      base_file: v001.txt
    1412f978aa0d4a239430d36bc8e75b5c:
      image_group_id: I1KG22020
      title: ''
      volume_number: 2
      total_pages: 1412
      base_file: v002.txt
