id: opecha:P006774
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8837
  title: གཞུང་ཆེན་བཅུ་གསུམ་གྱི་མཆན་འགྲེལ་ལས་མདོ་སྡེའི་རྒྱན་དང་ཤེར་ཕྱིན་སོགས་ཀྱི་མཆན་འགྲེལ་ཁག་ཅིག
  volume: ''
  author: ''
